version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root