version: '3.8'
services:

  db:
    image: postgres:latest
    container_name: postgres_db_recruitment
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DB_NAME=recruitment_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  app:
    restart: always
    build: .
    container_name: app_recruitment
    ports:
      - '8080:8080'
    depends_on: [ db ]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/recruitment