version: '3'

services:
  app:
    restart: always
    build: .
    container_name: app_recruitment
    ports:
      - '8080:8080'
    depends_on:
      - db
      - minio
    env_file:
      - .env
  db:
    image: postgres:latest
    container_name: postgres_db_recruitment
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

#  mongodb:
#    image: mongo:5.0.3
#    container_name: mongo_db_recruitment
#    restart: always
#    ports:
#      - "27017:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
#      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  minio:
      image: minio/minio:latest
      container_name: minio
      environment:
        - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
        - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      command: server ~/minio --console-address :9090
      ports:
        - '9090:9090'
        - '9000:9000'
      volumes:
        - minio-data:/minio

volumes:
  minio-data: