    version: '3.8'

    volumes:
      db-data:
        driver: local
      minio-data:
        driver: local

services:
  app:
    restart: always
    build:
      context: .
    container_name: recruitment_app
    ports:
      - '8080:8080'
    depends_on:
      - db
      - minio
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: postgres_db_recruitment
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./src/main/resources/liquibase:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio_data:/data

volumes:
  minio_data:
